
DEFAULT_WORD_LIMIT = 500
DEFAULT_TONE = "academic"
DEFAULT_TEMPERATURE = 0.7
MAX_WORD_LIMIT = 3000

FOCUS_BLOCK_MINUTES = 30
MIN_SESSION_MINUTES = 20

SUPPORTED_DIFFICULTIES = {"easy", "medium", "hard"}
